# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'
Rails.application.config.assets.precompile += %w( homes/index.css )
Rails.application.config.assets.precompile += %w( homes/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( env_selections/index.css )
Rails.application.config.assets.precompile += %w( env_selections/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( browser_selections/index.css )
Rails.application.config.assets.precompile += %w( browser_selections/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( select_safaris/index.css )
Rails.application.config.assets.precompile += %w( select_safaris/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( select_chromes/index.css )
Rails.application.config.assets.precompile += %w( select_chromes/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( select_pcs/index.css )
Rails.application.config.assets.precompile += %w( select_pcs/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( navbar.css )
Rails.application.config.assets.precompile += %w( places/index.css )
Rails.application.config.assets.precompile += %w( places/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( places/edit.css )
Rails.application.config.assets.precompile += %w( places/edit-rspnsv.css )
Rails.application.config.assets.precompile += %w( places/list.css )
Rails.application.config.assets.precompile += %w( places/list-rspnsv.css )
Rails.application.config.assets.precompile += %w( places/show.css )
Rails.application.config.assets.precompile += %w( places/show-rspnsv.css )
Rails.application.config.assets.precompile += %w( places/plus_place.css )
Rails.application.config.assets.precompile += %w( places/plus_place-rspnsv.css )
Rails.application.config.assets.precompile += %w( flash.css )
Rails.application.config.assets.precompile += %w( mymaps/new.css )
Rails.application.config.assets.precompile += %w( mymaps/new-rspnsv.css )
Rails.application.config.assets.precompile += %w( mymaps/search.css )
Rails.application.config.assets.precompile += %w( mymaps/search-rspnsv.css )
Rails.application.config.assets.precompile += %w( mymaps/show.css )
Rails.application.config.assets.precompile += %w( mymaps/show-rspnsv.css )
Rails.application.config.assets.precompile += %w( mymap_searchs/index.css )
Rails.application.config.assets.precompile += %w( mymap_searchs/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( mymap_searchs/recomend_mymaps.css )
Rails.application.config.assets.precompile += %w( mymap_searchs/recomend_mymaps-rspnsv.css )
Rails.application.config.assets.precompile += %w( mymap_searchs/following_mymaps.css )
Rails.application.config.assets.precompile += %w( mymap_searchs/following_mymaps-rspnsv.css )
Rails.application.config.assets.precompile += %w( users/show.css )
Rails.application.config.assets.precompile += %w( users/show-rspnsv.css )
Rails.application.config.assets.precompile += %w( users/show1.css )
Rails.application.config.assets.precompile += %w( users/show1-rspnsv.css )
Rails.application.config.assets.precompile += %w( users/profile.css )
Rails.application.config.assets.precompile += %w( users/profile-rspnsv.css )
Rails.application.config.assets.precompile += %w( users/edit.css )
Rails.application.config.assets.precompile += %w( users/edit-rspnsv.css )
Rails.application.config.assets.precompile += %w( user_searchs/index.css )
Rails.application.config.assets.precompile += %w( user_searchs/index-rspnsv.css )
Rails.application.config.assets.precompile += %w( user_searchs/recomend_users.css )
Rails.application.config.assets.precompile += %w( user_searchs/recomend_users-rspnsv.css )
Rails.application.config.assets.precompile += %w( user_searchs/following_users.css )
Rails.application.config.assets.precompile += %w( user_searchs/following_users-rspnsv.css )
Rails.application.config.assets.precompile += %w( user_searchs/facebook_users.css )
Rails.application.config.assets.precompile += %w( user_searchs/facebook_users-rspnsv.css )
# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
